// React/src/orig_App.js
import { useCallback } from 'react';

import 'devextreme/dist/css/dx.light.css';
import React from 'react';
import './App.css';

import { SelectBox } from 'devextreme-react/select-box';
import DataSource from 'devextreme/data/data_source';

import { data } from './data';

const dataSource = new DataSource({
    store: {
        data: data,
        type: 'array',
        key: 'ID'
    },
    group: 'Category'
});

const dropDownOptions = {
    height: 150
};

function App() {
    const onValueChanged = useCallback((e) => {
        console.log(e.previousValue);
        console.log(e.value);
    }, []);

    return (
        <div className="App">
            <SelectBox
                dataSource={dataSource}
                valueExpr="ID"
                displayExpr="Name"
                searchEnabled={true}
                onValueChanged={onValueChanged}
                label="Product"
                labelMode="floating"
                grouped={true}
                dropDownOptions={dropDownOptions}
            />
        </div>
    );
}

export default App;

// Angular/src/app/orig_app.component.ts
import { Component } from '@angular/core';
import DataSource from 'devextreme/data/data_source';
import { AppService, Item } from './app.service';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    dataSource: DataSource;
    data: Item[];
    dropDownOptions: any;

    constructor(service: AppService) {
        this.data = service.getItems();

        this.dataSource = new DataSource({
            store: {
                data: this.data,
                type: 'array',
                key: 'ID'
            },
            group: 'Category'
        });
        this.dropDownOptions = {
            height: 150
        };
    }

    onValueChanged(e) {
        console.log(e.previousValue);
        console.log(e.value);
    }
}
